### PR TITLE
fixed casing typo in dataDir const name

### PR DESCRIPTION
**Pull request by auxon**
Signed-off-by: auxon <richard.hein@gmail.com>

### CODE REVIEW

**Review by auxon — COMMENTED** [review]
f

**Review by auxon — COMMENTED** [review]
I guess this isn't going to be merged.

**Comment by shruggr** [comment]
Would you still like this (and the other) to be merged? I was away from the computer yesterday.

**Comment by auxon** [comment]
If you like.  Cheers!

**Comment by auxon** [comment]
Sorry I was busy to ... otherwise I would have been able to help more.

**Pull request closed without merging**
